services:

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mibasedatos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mibasedatos"]
      interval: 10s
      timeout: 5s
      retries: 5

  servicio1:
    image: servicio1:latest
    container_name: servicio1
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/mibasedatos
    depends_on:
      db:
        condition: service_healthy

  servicio2:
    image: servicio2:latest
    container_name: servicio2
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/mibasedatos
    depends_on:
      db:
        condition: service_healthy

  servicio3:
    image: servicio3:latest
    container_name: servicio3
    ports:
      - "4200:80"    # ← Puerto 80 interno (nginx), expuesto como 4200
    # Angular no necesita DATABASE_URL, elimínalo también
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/mibasedatos
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: